### ISSUE TITLE
FYI - forked due to name collision with SoftCircuits.CsvParser

### ISSUE THREAD

**Issue by joelverhagen** [bopohaa/CsvParser#3]
Hello, I just wanted to let you know that I have forked this project because it has the same assembly name and namespace as the following project: https://github.com/SoftCircuits/CsvParser

I am trying to test both libraries (and more) in my CSV parsing benchmark project here:
https://github.com/joelverhagen/NCsvPerf

My fork is here:
Package: https://www.nuget.org/packages/Knapcode.FastCsvParser
Repository: https://github.com/joelverhagen/Knapcode.FastCsvParser

I could not find an easier way to make both the "FastCsvParser" package (yours) and the "SoftCircuits.CsvParser" package run in the same project. I kept running into errors because both packages have "CsvParser.dll".

I tried to comply with your MIT license by referencing the original license in the package and I noted my changes.

**Comment by bopohaa** [comment]
Хорошая работа. Моя реализация уже давно устарела и требует полной переработки под новые возможности фреймворка позволяющие работать со срезами без лишних аллокаций памяти.

**Comment by bopohaa** [comment]
Good job. My implementation has long been outdated and requires a complete rework for the new framework capabilities that allow working with slices without unnecessary memory allocations.
